settingsdevice: fixed bug in settings-add and made unittest
The bug is a result of renaming _object to _proxy in commit
b6934b2fa2f770cf16d20dd6724f8433a9154b63. I forgot to change settingsdevice
accordingly back then. And this causes an error when adding settings:

File "ext/velib_python/settingsdevice.py", line 63, in __init__
....
AttributeError: 'VeDbusItemImport' object has no attribute 'get_object'

Solved for now by doing the same changed in settingsdevice, and I added a note
in vedbus.py about this. Should be replaced by a getter some day.

Also made a unittest that reproduced the problem.